### ISSUE TITLE
返回流

### ISSUE THREAD

**Issue by daixuyang** [houbb/iexcel#4]
Hi，希望能提供一个返回文件流的方法。方便请求的同时就可以返回文件流直接下载咯！

**Comment by houbb** [comment]
V 0.0.6 添加返回 byte[] 方法，可以自行构建流。

[ExcelBs#bytes() 获取文件字节内容](https://github.com/houbb/iexcel/blob/master/doc/user/04-ExcelBs-bytes-%E8%8E%B7%E5%8F%96%E6%96%87%E4%BB%B6%E5%AD%97%E8%8A%82%E4%BF%A1%E6%81%AF.md)

**Comment by daixuyang** [comment]
嘿嘿，感谢！
